import { useState, useEffect } from "react";

export const SubmitTimetable = () => {
    const [faculty, setFaculty] = useState([
        {
          name: "",
          days: [
            {
              day: "Monday",
              timeslots: [
                {
                  id: 1,
                  Timeslot: "",
                  Semester: "",
                  Division: "",
                  Classroom: "",
                  Subject: "",
                },
                {
                  id: 2,
                  Timeslot: "",
                  Semester: "",
                  Division: "",
                  Classroom: "",
                  Subject: "",
                },
                {
                  id: 3,
                  Timeslot: "",
                  Semester: "",
                  Division: "",
                  Classroom: "",
                  Subject: "",
                },
                {
                  id: 4,
                  Timeslot: "",
                  Semester: "",
                  Division: "",
                  Classroom: "",
                  Subject: "",
                },
                {
                  id: 5,
                  Timeslot: "",
                  Semester: "",
                  Division: "",
                  Classroom: "",
                  Subject: "",
                },
                {
                  id: 6,
                  Timeslot: "",
                  Semester: "",
                  Division: "",
                  Classroom: "",
                  Subject: "",
                },
                {
                  id: 7,
                  Timeslot: "",
                  Semester: "",
                  Division: "",
                  Classroom: "",
                  Subject: "",
                },
                {
                  id: 8,
                  Timeslot: "",
                  Semester: "",
                  Division: "",
                  Classroom: "",
                  Subject: "",
                },
              ],
            },
            {
              day: "Tuesday",
              timeslots: [
                {
                  id: 1,
                  Timeslot: "",
                  Semester: "",
                  Division: "",
                  Classroom: "",
                  Subject: "",
                },
                {
                  id: 2,
                  Timeslot: "",
                  Semester: "",
                  Division: "",
                  Classroom: "",
                  Subject: "",
                },
                {
                  id: 3,
                  Timeslot: "",
                  Semester: "",
                  Division: "",
                  Classroom: "",
                  Subject: "",
                },
                {
                  id: 4,
                  Timeslot: "",
                  Semester: "",
                  Division: "",
                  Classroom: "",
                  Subject: "",
                },
                {
                  id: 5,
                  Timeslot: "",
                  Semester: "",
                  Division: "",
                  Classroom: "",
                  Subject: "",
                },
                {
                  id: 6,
                  Timeslot: "",
                  Semester: "",
                  Division: "",
                  Classroom: "",
                  Subject: "",
                },
                {
                  id: 7,
                  Timeslot: "",
                  Semester: "",
                  Division: "",
                  Classroom: "",
                  Subject: "",
                },
                {
                  id: 8,
                  Timeslot: "",
                  Semester: "",
                  Division: "",
                  Classroom: "",
                  Subject: "",
                },
              ],
            },
            {
              day: "Wensday",
              timeslots: [
                {
                  id: 1,
                  Timeslot: "",
                  Semester: "",
                  Division: "",
                  Classroom: "",
                  Subject: "",
                },
                {
                  id: 2,
                  Timeslot: "",
                  Semester: "",
                  Division: "",
                  Classroom: "",
                  Subject: "",
                },
                {
                  id: 3,
                  Timeslot: "",
                  Semester: "",
                  Division: "",
                  Classroom: "",
                  Subject: "",
                },
                {
                  id: 4,
                  Timeslot: "",
                  Semester: "",
                  Division: "",
                  Classroom: "",
                  Subject: "",
                },
                {
                  id: 5,
                  Timeslot: "",
                  Semester: "",
                  Division: "",
                  Classroom: "",
                  Subject: "",
                },
                {
                  id: 6,
                  Timeslot: "",
                  Semester: "",
                  Division: "",
                  Classroom: "",
                  Subject: "",
                },
                {
                  id: 7,
                  Timeslot: "",
                  Semester: "",
                  Division: "",
                  Classroom: "",
                  Subject: "",
                },
                {
                  id: 8,
                  Timeslot: "",
                  Semester: "",
                  Division: "",
                  Classroom: "",
                  Subject: "",
                },
              ],
            },
            {
              day: "Thursday",
              timeslots: [
                {
                  id: 1,
                  Timeslot: "",
                  Semester: "",
                  Division: "",
                  Classroom: "",
                  Subject: "",
                },
                {
                  id: 2,
                  Timeslot: "",
                  Semester: "",
                  Division: "",
                  Classroom: "",
                  Subject: "",
                },
                {
                  id: 3,
                  Timeslot: "",
                  Semester: "",
                  Division: "",
                  Classroom: "",
                  Subject: "",
                },
                {
                  id: 4,
                  Timeslot: "",
                  Semester: "",
                  Division: "",
                  Classroom: "",
                  Subject: "",
                },
                {
                  id: 5,
                  Timeslot: "",
                  Semester: "",
                  Division: "",
                  Classroom: "",
                  Subject: "",
                },
                {
                  id: 6,
                  Timeslot: "",
                  Semester: "",
                  Division: "",
                  Classroom: "",
                  Subject: "",
                },
                {
                  id: 7,
                  Timeslot: "",
                  Semester: "",
                  Division: "",
                  Classroom: "",
                  Subject: "",
                },
                {
                  id: 8,
                  Timeslot: "",
                  Semester: "",
                  Division: "",
                  Classroom: "",
                  Subject: "",
                },
              ],
            },
            {
              day: "Friday",
              timeslots: [
                {
                  id: 1,
                  Timeslot: "",
                  Semester: "",
                  Division: "",
                  Classroom: "",
                  Subject: "",
                },
                {
                  id: 2,
                  Timeslot: "",
                  Semester: "",
                  Division: "",
                  Classroom: "",
                  Subject: "",
                },
                {
                  id: 3,
                  Timeslot: "",
                  Semester: "",
                  Division: "",
                  Classroom: "",
                  Subject: "",
                },
                {
                  id: 4,
                  Timeslot: "",
                  Semester: "",
                  Division: "",
                  Classroom: "",
                  Subject: "",
                },
                {
                  id: 5,
                  Timeslot: "",
                  Semester: "",
                  Division: "",
                  Classroom: "",
                  Subject: "",
                },
                {
                  id: 6,
                  Timeslot: "",
                  Semester: "",
                  Division: "",
                  Classroom: "",
                  Subject: "",
                },
                {
                  id: 7,
                  Timeslot: "",
                  Semester: "",
                  Division: "",
                  Classroom: "",
                  Subject: "",
                },
                {
                  id: 8,
                  Timeslot: "",
                  Semester: "",
                  Division: "",
                  Classroom: "",
                  Subject: "",
                },
              ],
            },
            {
              day: "Saturday",
              timeslots: [
                {
                  id: 1,
                  Timeslot: "",
                  Semester: "",
                  Division: "",
                  Classroom: "",
                  Subject: "",
                },
                {
                  id: 2,
                  Timeslot: "",
                  Semester: "",
                  Division: "",
                  Classroom: "",
                  Subject: "",
                },
                {
                  id: 3,
                  Timeslot: "",
                  Semester: "",
                  Division: "",
                  Classroom: "",
                  Subject: "",
                },
                {
                  id: 4,
                  Timeslot: "",
                  Semester: "",
                  Division: "",
                  Classroom: "",
                  Subject: "",
                },
                {
                  id: 5,
                  Timeslot: "",
                  Semester: "",
                  Division: "",
                  Classroom: "",
                  Subject: "",
                },
                {
                  id: 6,
                  Timeslot: "",
                  Semester: "",
                  Division: "",
                  Classroom: "",
                  Subject: "",
                },
                {
                  id: 7,
                  Timeslot: "",
                  Semester: "",
                  Division: "",
                  Classroom: "",
                  Subject: "",
                },
                {
                  id: 8,
                  Timeslot: "",
                  Semester: "",
                  Division: "",
                  Classroom: "",
                  Subject: "",
                },
              ],
            },
          ],
        },
    ]);

    return true;
};
