const timetable = {
  _id: "",
  semester: "",
  division: "",
  days: [
    {
      day: "Monday",
      timeslots: [
        {
          id: 1,
          Timeslot: "",
          Faculty: "",
          Classroom: "",
          Type: "",
          Subject: "",
        },
        {
          id: 2,
          Timeslot: "",
          Faculty: "",
          Classroom: "",
          Type: "",
          Subject: "",
        },
        {
          id: 3,
          Timeslot: "",
          Faculty: "",
          Classroom: "",
          Type: "",
          Subject: "",
        },
        {
          id: 4,
          Timeslot: "",
          Faculty: "",
          Classroom: "",
          Type: "",
          Subject: "",
        },
        {
          id: 5,
          Timeslot: "",
          Faculty: "",
          Classroom: "",
          Type: "",
          Subject: "",
        },
        {
          id: 6,
          Timeslot: "",
          Faculty: "",
          Classroom: "",
          Type: "",
          Subject: "",
        },
        {
          id: 7,
          Timeslot: "",
          Faculty: "",
          Classroom: "",
          Type: "",
          Subject: "",
        },
        {
          id: 8,
          Timeslot: "",
          Faculty: "",
          Classroom: "",
          Type: "",
          Subject: "",
        },
      ],
    },
    {
      day: "Tuesday",
      timeslots: [
        {
          id: 1,
          Timeslot: "",
          Faculty: "",
          Classroom: "",
          Type: "",
          Subject: "",
        },
        {
          id: 2,
          Timeslot: "",
          Faculty: "",
          Classroom: "",
          Type: "",
          Subject: "",
        },
        {
          id: 3,
          Timeslot: "",
          Faculty: "",
          Classroom: "",
          Type: "",
          Subject: "",
        },
        {
          id: 4,
          Timeslot: "",
          Faculty: "",
          Classroom: "",
          Type: "",
          Subject: "",
        },
        {
          id: 5,
          Timeslot: "",
          Faculty: "",
          Classroom: "",
          Type: "",
          Subject: "",
        },
        {
          id: 6,
          Timeslot: "",
          Faculty: "",
          Classroom: "",
          Type: "",
          Subject: "",
        },
        {
          id: 7,
          Timeslot: "",
          Faculty: "",
          Classroom: "",
          Type: "",
          Subject: "",
        },
        {
          id: 8,
          Timeslot: "",
          Faculty: "",
          Classroom: "",
          Type: "",
          Subject: "",
        },
      ],
    },
    {
      day: "Wednesday",
      timeslots: [
        {
          id: 1,
          Timeslot: "",
          Faculty: "",
          Classroom: "",
          Type: "",
          Subject: "",
        },
        {
          id: 2,
          Timeslot: "",
          Faculty: "",
          Classroom: "",
          Type: "",
          Subject: "",
        },
        {
          id: 3,
          Timeslot: "",
          Faculty: "",
          Classroom: "",
          Type: "",
          Subject: "",
        },
        {
          id: 4,
          Timeslot: "",
          Faculty: "",
          Classroom: "",
          Type: "",
          Subject: "",
        },
        {
          id: 5,
          Timeslot: "",
          Faculty: "",
          Classroom: "",
          Type: "",
          Subject: "",
        },
        {
          id: 6,
          Timeslot: "",
          Faculty: "",
          Classroom: "",
          Type: "",
          Subject: "",
        },
        {
          id: 7,
          Timeslot: "",
          Faculty: "",
          Classroom: "",
          Type: "",
          Subject: "",
        },
        {
          id: 8,
          Timeslot: "",
          Faculty: "",
          Classroom: "",
          Type: "",
          Subject: "",
        },
      ],
    },
    {
      day: "Thursday",
      timeslots: [
        {
          id: 1,
          Timeslot: "",
          Faculty: "",
          Classroom: "",
          Type: "",
          Subject: "",
        },
        {
          id: 2,
          Timeslot: "",
          Faculty: "",
          Classroom: "",
          Type: "",
          Subject: "",
        },
        {
          id: 3,
          Timeslot: "",
          Faculty: "",
          Classroom: "",
          Type: "",
          Subject: "",
        },
        {
          id: 4,
          Timeslot: "",
          Faculty: "",
          Classroom: "",
          Type: "",
          Subject: "",
        },
        {
          id: 5,
          Timeslot: "",
          Faculty: "",
          Classroom: "",
          Type: "",
          Subject: "",
        },
        {
          id: 6,
          Timeslot: "",
          Faculty: "",
          Classroom: "",
          Type: "",
          Subject: "",
        },
        {
          id: 7,
          Timeslot: "",
          Faculty: "",
          Classroom: "",
          Type: "",
          Subject: "",
        },
        {
          id: 8,
          Timeslot: "",
          Faculty: "",
          Classroom: "",
          Type: "",
          Subject: "",
        },
      ],
    },
    {
      day: "Friday",
      timeslots: [
        {
          id: 1,
          Timeslot: "",
          Faculty: "",
          Classroom: "",
          Type: "",
          Subject: "",
        },
        {
          id: 2,
          Timeslot: "",
          Faculty: "",
          Classroom: "",
          Type: "",
          Subject: "",
        },
        {
          id: 3,
          Timeslot: "",
          Faculty: "",
          Classroom: "",
          Type: "",
          Subject: "",
        },
        {
          id: 4,
          Timeslot: "",
          Faculty: "",
          Classroom: "",
          Type: "",
          Subject: "",
        },
        {
          id: 5,
          Timeslot: "",
          Faculty: "",
          Classroom: "",
          Type: "",
          Subject: "",
        },
        {
          id: 6,
          Timeslot: "",
          Faculty: "",
          Classroom: "",
          Type: "",
          Subject: "",
        },
        {
          id: 7,
          Timeslot: "",
          Faculty: "",
          Classroom: "",
          Type: "",
          Subject: "",
        },
        {
          id: 8,
          Timeslot: "",
          Faculty: "",
          Classroom: "",
          Type: "",
          Subject: "",
        },
      ],
    },
    {
      day: "Saturday",

      timeslots: [
        {
          id: 1,
          Timeslot: "",
          Faculty: "",
          Classroom: "",
          Type: "",
          Subject: "",
        },
        {
          id: 2,
          Timeslot: "",
          Faculty: "",
          Classroom: "",
          Type: "",
          Subject: "",
        },
        {
          id: 3,
          Timeslot: "",
          Faculty: "",
          Classroom: "",
          Type: "",
          Subject: "",
        },
        {
          id: 4,
          Timeslot: "",
          Faculty: "",
          Classroom: "",
          Type: "",
          Subject: "",
        },
        {
          id: 5,
          Timeslot: "",
          Faculty: "",
          Classroom: "",
          Type: "",
          Subject: "",
        },
        {
          id: 6,
          Timeslot: "",
          Faculty: "",
          Classroom: "",
          Type: "",
          Subject: "",
        },
        {
          id: 7,
          Timeslot: "",
          Faculty: "",
          Classroom: "",
          Type: "",
          Subject: "",
        },
        {
          id: 8,
          Timeslot: "",
          Faculty: "",
          Classroom: "",
          Type: "",
          Subject: "",
        },
      ],
    },
  ],
};
const availFaculty=[
    "A.N.V",
    "V.D",
    "A.J.T",
    "S.R.S",
  ]
export const ClearTimetableFields = (setTimetable,setAvailFaculty) => {
    setTimetable(timetable);
    setAvailFaculty(availFaculty);
};
